apiVersion: apps/v1
kind: Deployment
metadata:
  name: kano-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kano-integration
  strategy:
    type: Recreate
  template:
    metadata:
      labels:        
        app.kubernetes.io/component: kano-integration
    spec:
      containers:
        - image: {{ .Values.images.kano_integration.registry }}/{{ .Values.images.kano_integration.repository }}:{{ .Values.images.kano_integration.tag }}
          name: kano-integration
          args:
            - chirpstack-stream-consumer.mjs  
          env:            
            - name: REDIS_HOST
              value: {{ .Values.env.redis_host }}
            - name: REDIS_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: chirp-secret
                  key: redis_password
            {{- if .Values.env.mongodb.clean }}
            - name: MONGO_CLEAN
              value: "1"  
            {{- end}}          
            - name: MONGO_DB_NAME
              value: {{ .Values.env.mongodb.db }}
            - name: MONGO_USER
              value: {{ .Values.env.mongodb.user }}
            - name: MONGO_HOST
              value: {{ .Values.env.mongodb.host }}
            - name: MONGO_PASSWORD  
              valueFrom: 
                secretKeyRef:
                  name: chirp-secret
                  key: mongo_password     
          resources:
            limits:
              cpu: {{ .Values.resources.kano_integration.limits.cpu }}
              memory: {{ .Values.resources.kano_integration.limits.memory }}
            requests:
              cpu: {{ .Values.resources.kano_integration.requests.cpu }}
              memory: {{ .Values.resources.kano_integration.requests.memory }}       
          ports:            
          volumeMounts:       
      imagePullSecrets:
      - name: {{ .Values.images.pullSecret }}     
      restartPolicy: Always
      volumes:
      
        
            
