apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: chirpstack-gateway-bridge-basicstation
  name: chirpstack-gateway-bridge-basicstation
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    app.kubernetes.io/component: chirpstack-gateway-bridge-basicstation
