apiVersion: apps/v1
kind: Deployment
metadata:    
  name: chirpstack-gateway-bridge-basicstation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: chirpstack-gateway-bridge-basicstation
  strategy:
    type: Recreate
  template:
    metadata:      
      labels:        
        app.kubernetes.io/component: chirpstack-gateway-bridge-basicstation
    spec:
      containers:
        - args:
            - -c
            - /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml
          image: chirpstack/chirpstack-gateway-bridge:4
          name: chirpstack-gateway-bridge-basicstation
          ports:
            - containerPort: 3001
              hostPort: 3001
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/chirpstack-gateway-bridge
              name: vchirpstack-gateway-bridge-basicstation
      restartPolicy: Always
      volumes:
        - name: vchirpstack-gateway-bridge-basicstation
          configMap:
            name: chirpstack-gateway-bridge-conf
