apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: gateway-bridge
  name: chirpstack-gateway-bridge
spec:
  ports:
    - name: "1700"
      port: 1700
      protocol: UDP
      targetPort: 1700
  selector:
    app.kubernetes.io/component: gateway-bridge
