apiVersion: v1
kind: ConfigMap
metadata:
  name: chirpstack-gateway-bridge-conf
data:  
  chirpstack-gateway-bridge.toml: |
    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto:1883"]
    username=""
    password=""

  chirpstack-gateway-bridge-basicstation-eu868.toml: |
    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto:1883"]
    username=""
    password=""
    [integration.mqtt]
    event_topic_template="eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    state_topic_template="eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
    command_topic_template="eu868/gateway/{{ .GatewayID }}/command/#"
    [backend]
    type="basic_station"
      [backend.basic_station]
      bind=":3001"
      tls_cert=""
      tls_key=""
      ca_cert=""
      region="EU868"
      frequency_min=863000000
      frequency_max=870000000
      [[backend.basic_station.concentrators]]
        [backend.basic_station.concentrators.multi_sf]
        frequencies=[
          868100000,
          868300000,
          868500000,
          867100000,
          867300000,
          867500000,
          867700000,
          867900000,
        ]
        [backend.basic_station.concentrators.lora_std]
        frequency=868300000
        bandwidth=250000  
        spreading_factor=7
        [backend.basic_station.concentrators.fsk]
        frequency=868800000

  chirpstack-gateway-bridge-basicstation-in865.toml: |
    [integration.mqtt.auth.generic]
    servers=["tcp://mosquitto:1883"]
    username=""
    password=""
    [integration.mqtt]
    event_topic_template="in865/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    state_topic_template="in865/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
    command_topic_template="in865/gateway/{{ .GatewayID }}/command/#"
    [backend]
    type="basic_station"
      [backend.basic_station]
      bind=":3001"
      tls_cert=""
      tls_key=""
      ca_cert=""
      region="IN865"
      frequency_min=865000000
      frequency_max=867000000
      [[backend.basic_station.concentrators]]
        [backend.basic_station.concentrators.multi_sf]
        frequencies=[
          865062500,
          865402500,
          865985000,
        ]

