apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: networkServer
  name: chirpstack
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/component: networkServer
