apiVersion: v1
kind: Secret
metadata:
  name: chirp-secret
type: Opaque
data:
  redis_password: {{ .Values.env.redis_password }}
  postgresql_password: {{ .Values.env.postgres.password }}
  mongo_password: {{ .Values.env.mongodb.password | b64enc }}
