repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:

- name: minik-chirpstack
  namespace: chirpstack-dev
  chart: ./    
  values:
    - config/helmfile/{{`{{ .Environment.Name }}`}}/chirpstack.yaml
 
- name: postgres-bitnami
  namespace: chirpstack-dev
  chart: bitnami/postgresql
  values:
    - config/helmfile/{{`{{ .Environment.Name }}`}}/postgres.yaml
     
- name: redis-bitnami
  namespace: chirpstack-dev
  chart: bitnami/redis
  values:
    - config/helmfile/{{`{{ .Environment.Name }}`}}/redis.yaml

# 2 environments:
#  * minikube for development purpose
#  * demonstrator for the first official demonstrator
environments:
  minikube:
  demonstrator: