# chirpstack default values

global:
  # subdomain to be used when computing the ingress host
  subdomain: ""

env:
  fetch_lorawan_device: yes

  redis_host: "redis-master"
  redis_port: 6379
  redis_password: "password"
  
  postgres:
    host: postgres
    user: chirpstack

  # mongodDB
  mongodb:
    host: mongodb
    user: chirpstack
    password: chirpstack
    db: kano
    clean: false    

  # only for minikube testing, hardcoded value for node port
  mosquitto_node_port:
  networkserver_node_port:

  networkserver:
    admin_password: $pbkdf2-sha512$i=10000,l=32$8+wkKPD+g1rhQ7LmDafdmQ$9CkcCerTUyUf3fSPtyKcKZ5BmZio/DvEZuvRxSvGtnc # PBKDB2 hash

  kano_integration:
    # host that serve gRPC content, ex 'myhost:1111'
    grpc_host: "chirpstack:8080" 
    # a very long string, can be found in the chirpstack portal (network server API)
    grpc_token:    
    appSecret: ""
    mapillaryToken: ""
    cesiumToken: ""

  rest_api:
    # set yes to enable the legacy REST API
    enabled: no
# ingress
ingress:
  enabled: true
  className: nginx

images:
  kano_integration:
    registry: "harbor.portal.kalisio.com"
    repository: "kalisio/chirpstack-kano-integration"
    tag: "latest"
  pullSecret: ""

# resources for the different containers
resources:
  mosquitto:
    requests:
      cpu: "100m" 
      memory: "128Mi"         
    limits:
      cpu: "150m" 
      memory: "192Mi"
  rest_api:
    requests:
      cpu: "100m" 
      memory: "128Mi"         
    limits:
      cpu: "150m" 
      memory: "192Mi"
  gateway_bridge:
    requests:
      cpu: "100m" 
      memory: "128Mi"         
    limits:
      cpu: "150m" 
      memory: "192Mi"
  networkserver:
    requests:
      cpu: "100m" 
      memory: "128Mi"         
    limits:
      cpu: "300m" 
      memory: "398Mi"
  kano_integration:
    requests:
      cpu: "100m" 
      memory: "128Mi"         
    limits:
      cpu: "300m" 
      memory: "398Mi" 
  