apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yml convert -c
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: chirpstack-gateway-bridge-basicstation
  name: chirpstack-gateway-bridge-basicstation
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: chirpstack-gateway-bridge-basicstation
