apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yml convert -c
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: chirpstack-gateway-bridge
  name: chirpstack-gateway-bridge
spec:
  ports:
    - name: "1700"
      port: 1700
      protocol: UDP
      targetPort: 1700
  selector:
    io.kompose.service: chirpstack-gateway-bridge
