apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yml convert -c
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: chirpstack-gateway-bridge-basicstation
  name: chirpstack-gateway-bridge-basicstation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chirpstack-gateway-bridge-basicstation
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.yml convert -c
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/chirpstack-kompose-default: "true"
        io.kompose.service: chirpstack-gateway-bridge-basicstation
    spec:
      containers:
        - args:
            - -c
            - /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-eu868.toml
          image: chirpstack/chirpstack-gateway-bridge:4
          name: chirpstack-gateway-bridge-basicstation
          ports:
            - containerPort: 3001
              hostPort: 3001
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/chirpstack-gateway-bridge
              name: vchirpstack-gateway-bridge-basicstation
      restartPolicy: Always
      volumes:
        - name: vchirpstack-gateway-bridge-basicstation
          configMap:
            name: chirpstack-gateway-bridge-conf
