apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: chirpstack
  name: chirpstack
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: chirpstack
