apiVersion: v1
kind: ConfigMap
metadata:
  name: chirpstack-config
data:  
  chirpstack.toml: |
    [logging]
    level="info"
    [postgresql]
    dsn="postgres://chirpstack:chirpstack@$POSTGRESQL_HOST/chirpstack?sslmode=disable"
    max_open_connections=10
    min_idle_connections=0
    [redis]
    servers=[
      "redis://$REDIS_HOST/",
    ]
    tls_enabled=false
    cluster=false
    [network]
    net_id="000000"
    # only EU regions  
    enabled_regions=[    
      "eu868",
      "in865"      
    ]
    # API interface configuration.
    [api]  
    bind="0.0.0.0:8080"
    secret="you-must-replace-this"
    [integration]
    enabled=["mqtt"]
    [integration.mqtt]
      server="tcp://$MQTT_BROKER_HOST:1883/"
      json=true

  region_eu868.toml: |
    [[regions]]
      id="eu868"
      description="EU868"
      common_name="EU868"
      [regions.gateway]
        force_gws_private=false
        [regions.gateway.backend]
          enabled="mqtt"
          [regions.gateway.backend.mqtt]
            topic_prefix="eu868"
            server="tcp://$MQTT_BROKER_HOST:1883"
            username=""
            password=""
            qos=0
            clean_session=false
            client_id=""
            keep_alive_interval="30s"
            ca_cert=""
            tls_cert=""
            tls_key=""
        [[regions.gateway.channels]]
          frequency=868100000
          bandwidth=125000
          modulation="LORA"
          spreading_factors=[7, 8, 9, 10, 11, 12]
        [[regions.gateway.channels]]
          frequency=868300000
          bandwidth=125000
          modulation="LORA"
          spreading_factors=[7, 8, 9, 10, 11, 12]
        [[regions.gateway.channels]]
          frequency=868500000
          bandwidth=125000
          modulation="LORA"
          spreading_factors=[7, 8, 9, 10, 11, 12]
        [[regions.gateway.channels]]
          frequency=867100000
          bandwidth=125000
          modulation="LORA"
          spreading_factors=[7, 8, 9, 10, 11, 12]
        [[regions.gateway.channels]]
          frequency=867300000
          bandwidth=125000
          modulation="LORA"
          spreading_factors=[7, 8, 9, 10, 11, 12]
        [[regions.gateway.channels]]
          frequency=867500000
          bandwidth=125000
          modulation="LORA"
          spreading_factors=[7, 8, 9, 10, 11, 12]
        [[regions.gateway.channels]]
          frequency=867700000
          bandwidth=125000
          modulation="LORA"
          spreading_factors=[7, 8, 9, 10, 11, 12]
        [[regions.gateway.channels]]
          frequency=867900000
          bandwidth=125000
          modulation="LORA"
          spreading_factors=[7, 8, 9, 10, 11, 12]
        [[regions.gateway.channels]]
          frequency=868300000
          bandwidth=250000
          modulation="LORA"
          spreading_factors=[7]
        [[regions.gateway.channels]]
          frequency=868800000
          bandwidth=125000
          modulation="FSK"
          datarate=50000
      [regions.network]
        installation_margin=10
        rx_window=0
        rx1_delay=1
        rx1_dr_offset=0
        rx2_dr=0
        rx2_frequency=869525000
        rx2_prefer_on_rx1_dr_lt=0
        rx2_prefer_on_link_budget=false
        downlink_tx_power=-1
        adr_disabled=false
        min_dr=0
        max_dr=5
        [regions.network.rejoin_request]
          enabled=false
          max_count_n=0
          max_time_n=0
        [regions.network.class_b]
          ping_slot_dr=3
          ping_slot_frequency=0
        [[regions.network.extra_channels]]
        frequency=867100000
        min_dr=0
        max_dr=5
        [[regions.network.extra_channels]]
        frequency=867300000
        min_dr=0
        max_dr=5
        [[regions.network.extra_channels]]
        frequency=867500000
        min_dr=0
        max_dr=5
        [[regions.network.extra_channels]]
        frequency=867700000
        min_dr=0
        max_dr=5
        [[regions.network.extra_channels]]
        frequency=867900000
        min_dr=0
        max_dr=5
  
  region_in865.toml: |
    [[regions]]
      id="in865"
      description="IN865"
      common_name="IN865"
      [regions.gateway]
        force_gws_private=false
        [regions.gateway.backend]
          enabled="mqtt"
          [regions.gateway.backend.mqtt]
            topic_prefix="in865"
            server="tcp://$MQTT_BROKER_HOST:1883"
            username=""
            password=""
            qos=0
            clean_session=false
            client_id=""
            keep_alive_interval="30s"
            ca_cert=""
            tls_cert=""
            tls_key=""
        [[regions.gateway.channels]]
          frequency=865062500
          bandwidth=125000
          modulation="LORA"
          spreading_factors=[7, 8, 9, 10, 11, 12]
        [[regions.gateway.channels]]
          frequency=865402500
          bandwidth=125000
          modulation="LORA"
          spreading_factors=[7, 8, 9, 10, 11, 12]
        [[regions.gateway.channels]]
          frequency=865985000
          bandwidth=125000
          modulation="LORA"
          spreading_factors=[7, 8, 9, 10, 11, 12]
      [regions.network]
        installation_margin=10
        rx_window=0
        rx1_delay=1
        rx1_dr_offset=0
        rx2_dr=2
        rx2_frequency=866550000
        rx2_prefer_on_rx1_dr_lt=0
        rx2_prefer_on_link_budget=false
        downlink_tx_power=-1
        adr_disabled=false
        min_dr=0
        max_dr=5
        [regions.network.rejoin_request]
          enabled=false
          max_count_n=0
          max_time_n=0
        [regions.network.class_b]
          ping_slot_dr=4
          ping_slot_frequency=0



      