apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:    
    app.kubernetes.io/component: networkserver    
  name: chirpstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: networkServer
  strategy:
    type: Recreate
  template:
    metadata:      
      labels:        
        app.kubernetes.io/component: networkServer
        app.kubernetes.io/part-of: chirstack
        app.kubernetes.io/version: {{ .Chart.AppVersion }}        
    spec:
      containers:
        - args:
            - -c
            - /etc/chirpstack
          env:
            - name: MQTT_BROKER_HOST
              value: mosquitto
            - name: POSTGRESQL_HOST
              value: {{ .Values.env.postgres_host }}
            - name: REDIS_HOST
              value: {{ .Values.env.redis_host }}
            - name: REDIS_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: chirp-secret
                  key: redis_password
            - name: POSTGRESQL_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: chirp-secret
                  key: postgresql_password
          image: chirpstack/chirpstack:4
          name: chirpstack
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/chirpstack
              name: vchirpstack-config            
      restartPolicy: Always
      volumes:
        - name: vchirpstack-config
          configMap:
            name: chirpstack-config
        - name: chirpstack-claim1
          persistentVolumeClaim:
            claimName: chirpstack-claim1
      # init container is used to fetch lorawan devices and import them into the postgreSQL
      initContainers:
        - name: fetch-lorawan-devices
          image: chirpstack/chirpstack:4
          command: ['sh', '-c', 'apk add --no-cache git && git clone https://github.com/brocaar/lorawan-devices /opt/lorawan-devices && chirpstack -c /etc/chirpstack import-legacy-lorawan-devices-repository -d /opt/lorawan-devices; sleep 60']          
          env:            
            - name: POSTGRESQL_HOST
              value: {{ .Values.env.postgres_host }}
            - name: REDIS_HOST
              value: {{ .Values.env.redis_host }}
            - name: REDIS_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: chirp-secret
                  key: redis_password
            - name: POSTGRESQL_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: chirp-secret
                  key: postgresql_password
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /etc/chirpstack
              name: vchirpstack-config
            - mountPath: /opt/lorawan-devices
              name: chirpstack-claim1      
