apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yml convert -c
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: chirpstack
  name: chirpstack
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chirpstack
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.yml convert -c
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/chirpstack-kompose-default: "true"
        io.kompose.service: chirpstack
    spec:
      containers:
        - args:
            - -c
            - /etc/chirpstack
          env:
            - name: MQTT_BROKER_HOST
              value: mosquitto
            - name: POSTGRESQL_HOST
              value: {{ .Values.env.postgres_host }}
            - name: REDIS_HOST
              value: {{ .Values.env.redis_host }}
            - name: REDIS_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: chirp-secret
                  key: redis_password
          image: chirpstack/chirpstack:4
          name: chirpstack
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/chirpstack
              name: vchirpstack-config            
      restartPolicy: Always
      volumes:
        - name: vchirpstack-config
          configMap:
            name: chirpstack-config
        - name: chirpstack-claim1
          persistentVolumeClaim:
            claimName: chirpstack-claim1
      # init container is used to fetch lorawan devices and import them into the postgreSQL
      initContainers:
        - name: fetch-lorawan-devices
          image: chirpstack/chirpstack:4
          command: ['sh', '-c', 'apk add --no-cache git && git clone https://github.com/brocaar/lorawan-devices /opt/lorawan-devices && chirpstack -c /etc/chirpstack import-legacy-lorawan-devices-repository -d /opt/lorawan-devices; sleep 60']          
          env:            
            - name: POSTGRESQL_HOST
              value: {{ .Values.env.postgres_host }}
            - name: REDIS_HOST
              value: {{ .Values.env.redis_host }}
            - name: REDIS_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: chirp-secret
                  key: redis_password
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /etc/chirpstack
              name: vchirpstack-config
            - mountPath: /opt/lorawan-devices
              name: chirpstack-claim1      
