apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  ports:
    - name: "1883"
      port: 1883
      targetPort: 1883
  selector:
    io.kompose.service: mosquitto
