apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yml convert -c
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.yml convert -c
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/chirpstack-kompose-default: "true"
        io.kompose.service: mosquitto
    spec:
      containers:
        - image: eclipse-mosquitto:2
          name: mosquitto
          ports:
            - containerPort: 1883
              hostPort: 1883
              protocol: TCP
          volumeMounts:
            - mountPath: /mosquitto/config
              name: vmosquitto-config
      restartPolicy: Always
      volumes:
        - name: vmosquitto-config
          configMap:
            name: mosquittoconfig
            
