apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initscripts
data:  
  001-init-chirpstack.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        create role chirpstack with login password 'chirpstack';
        create database chirpstack with owner chirpstack;
    EOSQL

  002-chirpstack_extensions.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="chirpstack" <<-EOSQL
        create extension pg_trgm;
        create extension hstore;
    EOSQL

  