[logging]
    level="debug"

[postgresql]
    dsn="postgres://chirpstack:$POSTGRESQL_PASSWORD@$POSTGRESQL_HOST/chirpstack?sslmode=disable"
    max_open_connections=10
    min_idle_connections=0

[redis]
    servers=[
        "redis://:$REDIS_PASSWORD@$REDIS_HOST/",
    ]
    tls_enabled=false
    cluster=false

[network]
    net_id="000000"
    # only EU regions  
    enabled_regions=[    
        "eu868",
        "in865"      
    ]

# API interface configuration.
[api]  
    bind="0.0.0.0:8080"
    secret="you-must-replace-this"

[integration]
    enabled=["mqtt"]
    [integration.mqtt]
        server="tcp://$MQTT_BROKER_HOST:1883/"
        json=true

[monitoring]
  
  backend_interfaces_log_max_history=10
  meta_log_max_history=10
  gateway_frame_log_max_history=10
  device_frame_log_max_history=10
  device_event_log_max_history=10
  per_gateway_frame_log_max_history=10
  per_gateway_frame_log_ttl="1month 13h 26m 24s"
  per_device_frame_log_max_history=10
  per_device_frame_log_ttl="1month 13h 26m 24s"
  per_device_event_log_max_history=10
  per_device_event_log_ttl="1month 13h 26m 24s"