[logging]
    level="debug"

[postgresql]
    dsn="postgres://chirpstack:$POSTGRESQL_PASSWORD@$POSTGRESQL_HOST/chirpstack?sslmode=disable"
    max_open_connections=10
    min_idle_connections=0

[redis]
    servers=[
        "redis://:$REDIS_PASSWORD@$REDIS_HOST/",
    ]
    tls_enabled=false
    cluster=false

[network]
    net_id="000000"
    # only EU regions  
    enabled_regions=[    
        "eu868",
        "in865"      
    ]

# API interface configuration.
[api]  
    bind="0.0.0.0:8080"
    secret="you-must-replace-this"

[integration]
    enabled=["mqtt"]
    [integration.mqtt]
        server="tcp://$MQTT_BROKER_HOST:1883/"
        json=true

[monitoring]
  
  backend_interfaces_log_max_history=10
  meta_log_max_history=10
  gateway_frame_log_max_history=10
  device_frame_log_max_history=10
  device_event_log_max_history=10
  per_gateway_frame_log_max_history=10
  per_gateway_frame_log_ttl="1month 13h 26m 24s"
  per_device_frame_log_max_history=10
  per_device_frame_log_ttl="1month 13h 26m 24s"
  per_device_event_log_max_history=10
  per_device_event_log_ttl="1month 13h 26m 24s"

# User authentication configuration.
[user_authentication]
  enabled="openid_connect"
  [user_authentication.openid_connect]

    # Registration disabled.
    registration_enabled=false    
    registration_callback_url=""    
    provider_url="https://keycloak.{{ .Values.global.subdomain }}/auth/realms/chirpstack"
    client_id="{{ .Values.env.keycloak.client_id }}"
    client_secret="{{ .Values.env.keycloak.client_secret }}"    
    redirect_url="https://chirpstack.{{ .Values.global.subdomain }}/auth/oidc/callback"    
    logout_url=""
    login_redirect=false
    login_label="keycloak"
    assume_email_verified=false

