# chirpstack values for minikube environment

global:
  # subdomain to be used when computing the ingress host
  subdomain: "test"
  certIssuer: ""

env:  
  fetch_lorawan_device: no
  redis_password: VGhlUmVkaXNQd2Qh  # base 64 encoded
  postgres:
    host: postgres-postgresql 
    user: chirpstack
    db: chirpstack
    password: Y2hpcnBzdGFjaw== # base 64 encoded
  
  mongodb:
    host: mongodb
    user: chirpstack
    password: chirpstack 
    db: kano 
    clean: false # use for development purpose    

  # require to generate the secret for Kano integration
  kano_integration:
    appSecret: "MyKanoSecret"
    mapillaryToken: ""
    cesiumToken: ""    
    grpc_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6IjhhNjVjYmRhLTgyYzMtNGQ1MS05YzQ2LTBiN2NiMjU2MDRjOCIsInR5cCI6ImtleSJ9.JFal9wQB20pORaO8-ANffM1J8q-hozoj1r6pskohAKo"

  # keycloak
  keycloak:
    client_id: k-keycloack-chirpstack
    client_secret: qFYAudPwE5IWDsGoaDdQeQyz1QU7WF01

images:
  pullSecret: "kalisio-harbor"
