# chirpstack values for minikube environment

global:
  # subdomain to be used when computing the ingress host
  subdomain: "test"
  certIssuer: ""

env:  
  fetch_lorawan_device: no
  redis_password: VGhlUmVkaXNQd2Qh  # base 64 encoded
  postgres:
    host: postgres-postgresql 
    user: chirpstack
    db: chirpstack
    password: Y2hpcnBzdGFjaw== # base 64 encoded
  
  mongodb:
    host: mongodb
    user: chirpstack
    password: chirpstack 
    db: kano 
    clean: false # use for development purpose    

  # require to generate the secret for Kano integration
  kano_integration:
    appSecret: "MyKanoSecret"
    mapillaryToken: ""
    cesiumToken: ""
    gatewayConfig: |
      {
      "24e124fffef460b4": {
        "lat": 43.600443297757835, 
        "lon": 1.419038772583008, 
        "desc": "MileSight GW (Romain)"},
      "0016c001f10fca1d":  {
        "lat": 43.5781632, 
        "lon": 1.4516224, 
        "desc": "RaspBerry DIY GW (Adrien)"}
      }

images:
  pullSecret: "kalisio-harbor"
