# postgres values for minikube environment

#default user and db
auth:
  postgresPassword: Root
  username: chirpstack
  password: chirpstack
  database: chirpstack

# required extensions for chirpstack
primary:
  initdb:
    scripts:
      001-chirpstack_extensions.sql: |
        create extension pg_trgm;
        create extension hstore;

# persistance
# 50 Mi are already taken at initial import for LoRaWAN devices
# we don't use the postgres integration
primary:
  persistence:
    size: 100Mi

# from the nano definition of the bitnami preset
# this is a demonstrator so nano is enough
primary.resources:
  requests:
    cpu: "100m" 
    memory: "128Mi" 
    ephemeral-storage: "50Mi"
  limits:
    cpu: "150m" 
    memory: "192Mi"
    ephemeral-storage: "1024Mi"
