# postgres values for minikube environment
# used by chirpstack for configuraiton and by Keycloak
#default user postgres
auth:
  postgresPassword: Root

# persistance
# 50 Mi are already taken at initial import for LoRaWAN devices
# we don't use the postgres integration
primary:
  persistence:
    size: 100Mi
  # from the nano definition of the bitnami preset
  # this is a demonstrator so nano is enough
  resources:
    requests:
      cpu: "100m" 
      memory: "128Mi" 
      ephemeral-storage: "100Mi"
    limits:
      cpu: "150m" 
      memory: "192Mi"
      ephemeral-storage: "1024Mi"
  initdb:
    # required extensions for chirpstack
    scripts:      
      002-keycloak.sql: |-
        CREATE DATABASE keycloak;
        \c keycloak;
        CREATE USER keycloak WITH PASSWORD 'keycloak';
        ALTER DATABASE keycloak OWNER TO keycloak;
      001-chirpstack.sql: |-
        CREATE DATABASE chirpstack;
        \c chirpstack;
        CREATE USER chirpstack WITH PASSWORD 'chirpstack';
        ALTER DATABASE chirpstack OWNER TO chirpstack;
        CREATE EXTENSION IF NOT EXISTS "pg_trgm";
        CREATE EXTENSION IF NOT EXISTS "hstore";



